import assert from 'node:assert/strict';
import {existsSync} from 'node:fs';
assert(existsSync('src/utils/dailyWork.ts'),'Daily work rules must exist');
const {remindersFor, dataWarnings, isMine, malaysiaToday, validateIgnoredWarnings}=await import('../src/utils/dailyWork');
const row:any={id:1,property:'Test',status:'Active',date:'08/10/2026',propertyGuruRepostDate:'2026-09-30',createdByUserId:'7',createdByName:'Creator',noTel:'Not captured'};
assert.equal(malaysiaToday(new Date('2026-09-30T16:01:00Z')),'2026-10-01');
assert.equal(remindersFor(row,'2026-10-01').length,2);
assert.equal(remindersFor({...row,date:'09/10/2026',propertyGuruRepostDate:null},'2026-10-01').length,0);
assert.equal(remindersFor({...row,date:'01/10/2026',propertyGuruRepostDate:null},'2026-10-01')[0].days,0);
assert.equal(remindersFor({...row,status:'Sold Out'},'2026-10-01').length,0);
assert.equal(remindersFor({...row,archivedAt:'2026-10-01'},'2026-10-01').length,0);
assert.equal(remindersFor({...row,date:'1.10',propertyGuruRepostDate:null},'2026-10-01').length,0);
assert.equal(remindersFor({...row,date:'31/02/2026',propertyGuruRepostDate:null},'2026-10-01').length,0);
assert(dataWarnings({...row,date:'1.10'},0).some(w=>w.key==='expiry'));
assert(!dataWarnings(row,undefined).some(w=>w.key==='links'));
assert(dataWarnings(row,0).some(w=>w.key==='links'));
assert(dataWarnings(row,1).some(w=>w.key==='phone'));
assert(!dataWarnings({...row,noTel:'0123456789'},1).some(w=>w.key==='phone'));
assert(isMine(row,{id:7,displayName:'Renamed',username:'creator'}));
assert(!isMine(row,{id:8,displayName:'Creator',username:'other'}));
assert(isMine({...row,createdByUserId:null},{id:8,displayName:'Creator',username:'other'}));
assert.deepEqual(validateIgnoredWarnings(['phone','links']),['phone','links']);
assert.throws(()=>validateIgnoredWarnings(['anything']));
assert.throws(()=>validateIgnoredWarnings('phone'));
console.log('PASS Malaysia date boundaries, seven-day reminders, no invented years, sold/archive exclusion, completeness, PIC ownership and ignore validation');
