import assert from 'node:assert/strict';
import { existsSync, readFileSync } from 'node:fs';
import { PGlite } from '@electric-sql/pglite';
assert.ok(existsSync('src/utils/listingPresentation.ts'),'Creator and renewal presentation must exist');
const { creatorLabel, renewalRowClass, validatePriority } = await import('../src/utils/listingPresentation');
assert.equal(creatorLabel({createdByName:null}), 'Creator not recorded');
assert.equal(creatorLabel({createdByName:'Creator'}), 'Creator');
assert.equal(renewalRowClass('Renewed'),'bg-emerald-50');
assert.equal(renewalRowClass('Want to be renew'),'bg-orange-50');
assert.equal(renewalRowClass('Not Renewed'),'bg-white');
assert.deepEqual(validatePriority({}),{});
assert.deepEqual(validatePriority({isPriority:false}),{isPriority:false});
for(const isPriority of ['true',1,null])assert.throws(()=>validatePriority({isPriority}));
const pg=new PGlite();
try {
 await pg.exec(`CREATE TABLE listings(id serial PRIMARY KEY,property text,project_category text,location text,tenure text,pm text,negotiator text,agent text,no_tel text,available_units text,status text,date text,renew_status text,notes text,updated_by_user_id text,updated_by_name text,updated_by_email text,last_updated_at timestamp,created_at timestamp DEFAULT now());
 CREATE TABLE owner_listings(id serial PRIMARY KEY,property_name text);
 INSERT INTO owner_listings(property_name) VALUES ('Unchanged owner');
 INSERT INTO listings(property,pm,negotiator,agent,updated_by_name) VALUES ('Existing','Old PM','Negotiator','Agent','Last editor');`);
 await pg.exec(readFileSync('drizzle/0001_publication_channels.sql','utf8'));
 const original=(await pg.query('SELECT to_jsonb(t) AS row FROM listings t')).rows;
 const owner=(await pg.query('SELECT * FROM owner_listings')).rows;
 await pg.exec(readFileSync('drizzle/0002_listing_creator_priority.sql','utf8'));
 assert.deepEqual((await pg.query("SELECT to_jsonb(t)-'created_by_user_id'-'created_by_name'-'is_priority' AS row FROM listings t")).rows,original);
 assert.deepEqual((await pg.query('SELECT * FROM owner_listings')).rows,owner);
 const legacy=(await pg.query<any>('SELECT * FROM listings')).rows[0];
 assert.equal(legacy.created_by_name,null);assert.equal(legacy.is_priority,false);
 const services:any={getSessionUser:async()=>({id:7,username:'creator',displayName:'Original Creator',role:'user'}),getDb:()=>({query:async(sql:string,params:unknown[])=>(await pg.query(sql,params)).rows})};
 const {onRequestPost}=await import('../functions/api/listings');
 const {onRequestPatch}=await import('../functions/api/listings/[id]');
 const request=(body:unknown)=>new Request('https://example.com/api/listings',{method:'POST',body:JSON.stringify(body)});
 const response=await onRequestPost({env:{DATABASE_URL:'test'},request:request({property:'New',location:'KL',pm:'Lister',negotiator:'Negotiator',agent:'Agent',isPriority:true,createdByName:'Spoof',createdByUserId:'999'})},services);
 assert.equal(response.status,201);const created=(await response.json()).data;
 assert.equal(created.createdByName,'Original Creator');assert.equal(created.createdByUserId,'7');assert.equal(created.pm,'Lister');assert.equal(created.isPriority,true);
 services.getSessionUser=async()=>({id:8,username:'editor',displayName:'Different Editor',role:'user'});
 const patch=await onRequestPatch({env:{DATABASE_URL:'test'},params:{id:String(created.id)},request:request({isPriority:false,createdByName:'Spoof',createdByUserId:'999'})},services);
 assert.equal(patch.status,200);const edited=(await patch.json()).data;
 assert.equal(edited.isPriority,false);assert.equal(edited.createdByName,'Original Creator');assert.equal(edited.updatedByName,'Different Editor');
 for(const field of ['pm','negotiator','agent'])assert.equal(edited[field],created[field]);
 const untouched=await onRequestPatch({env:{DATABASE_URL:'test'},params:{id:String(created.id)},request:request({notes:'Only notes changed'})},services);
 assert.equal((await untouched.json()).data.isPriority,false);
 const invalid=await onRequestPatch({env:{DATABASE_URL:'test'},params:{id:String(created.id)},request:request({isPriority:'yes'})},services);assert.equal(invalid.status,400);
 services.getSessionUser=async()=>null;
 assert.equal((await onRequestPost({env:{DATABASE_URL:'test'},request:request({})},services)).status,401);
 console.log('PASS creator from session, immutable on edit, shared priority persistence/validation, PM and legacy data preservation, renewal colors and unknown legacy creators');
} finally {await pg.close();}
