import assert from 'node:assert/strict';
import {existsSync} from 'node:fs';
assert(existsSync('src/reportExport.ts'),'Report export formatter exists');
const {buildPublicationReport}=await import('../src/reportExport');
const channels:any=[{id:1,name:'Telegram',archivedAt:null},{id:2,name:'Mudah',archivedAt:null},{id:3,name:'Old channel',archivedAt:'2026-01-01'},{id:4,name:'Unused archived',archivedAt:'2026-01-01'}];
const listing:any={property:'E Sentral',location:'Shah Alam',pm:'Nor Ozir',noTel:'60122980810'};
const links:any=[{id:1,channelId:1,url:'https://t.me/example/808',label:'Channel NHC'},{id:2,channelId:1,url:'https://t.me/example/809',label:'Personal'},{id:3,channelId:3,url:'https://example.com/old',label:null}];
const report=buildPublicationReport(listing,links,channels);
assert(report.includes('*E Sentral – Shah Alam*'));
assert(report.includes('LISTER\nNAME : Nor Ozir\nTEL : 60122980810'));
assert(report.includes('1. Telegram\nChannel NHC: https://t.me/example/808\nPersonal: https://t.me/example/809'));
assert(report.includes('2. Mudah\nN/A'));
assert(report.includes('3. Old channel\nhttps://example.com/old'));
assert(!report.includes('Unused archived'));
assert(!report.includes('OWNER LISTING'));
assert(!report.includes('RM'));
assert.equal(report.split('https://t.me/example/808').length,2);
assert(buildPublicationReport({...listing,pm:'',noTel:''},[],[]).includes('NAME : N/A\nTEL : N/A'));
assert(buildPublicationReport(listing,[{channelId:99,url:'https://example.com/unknown'}] as any,[]).includes('https://example.com/unknown'));
console.log('PASS grouped categories, labels, multiple links, N/A, archived links retained, unknown category fallback and no invented owner/price');
